spring.application.name=travelmatch

#spring.datasource.url=jdbc:mysql://localhost:3306/travelmatch

spring.datasource.username=root
#spring.datasource.password=Pritam+#@1000

spring.datasource.url=jdbc:mysql://root:AZKAoBCqxXTKDbyNBwMHyDvtUEPHPfhr@mysql.railway.internal:3306/railway
spring.datasource.password=AZKAoBCqxXTKDbyNBwMHyDvtUEPHPfhr
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
server.port=8080
resend.api.key=${RESEND_API_KEY}



